embedding_size: 64              # (int) The embedding size of users and items.
dropout_prob: 0.4               # (float) The dropout rate. 
reg_weight: 1e-4                # (float) The L2 regularization weight.
nv: 4                           # (int) The number of vertical Convolutional filters.
nh: 8                           # (int) The number of horizontal Convolutional filters.
loss_type: 'CE'                 # (str) The type of loss function.

gpu_id: '0'
log_wandb: False


d_state: 32                     # (int) SSM state expansion factor
d_conv: 4                       # (int) Local convolution width
expand: 2                       # (int) Block expansion factor


# dataset settings
dataset: Beauty
MAX_ITEM_LIST_LENGTH: 50       # 200 for MovieLens-1M

USER_ID_FIELD: user_id
ITEM_ID_FIELD: item_id
load_col:
    inter: [user_id, item_id, timestamp]

user_inter_num_interval: "[5,inf)"
item_inter_num_interval: "[5,inf)"

# training settings
epochs: 300
train_batch_size: 2048
learner: adam
learning_rate: 0.001
eval_step: 1
stopping_step: 5
train_neg_sample_args: ~



# evalution settings
metrics: ['Hit', 'NDCG', 'MRR']
valid_metric: Hit@20
eval_batch_size: 4096
weight_decay: 0.0
topk: [5,10,20]



lmd: 0.1
tau: 1
